export const THEME_STORAGE_KEY = "@app_theme_v1";
export const DEFAULT_THEME_ID = "lightIndustrial";

const lightIndustrial = Object.freeze({
  canvas: "#F5F8FC",
  canvasSoft: "#F9FBFE",
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surfaceAlt: "#EEF3F8",
  surfaceStrong: "#DCE4EC",
  textPrimary: "#0D1A2A",
  textSecondary: "#314660",
  textMuted: "#48607A",
  textInverse: "#FFFFFF",
  border: "#DCE4EC",
  borderStrong: "#8FA4BB",
  borderFocus: "#59A7D6",
  brand: "#1F5E8D",
  brandDark: "#0F3657",
  brandSoft: "#E9F2FA",
  accent: "#E0921A",
  accentSoft: "#FFF2DB",
  info: "#2E9BCC",
  success: "#1F9D62",
  warning: "#C97808",
  danger: "#D04545",
  focusRing: "#59A7D6",
  white: "#FFFFFF",
  black: "#000000",
  navActive: "#0F3657",
  navInactive: "#607A95",
  navIndicator: "#E0921A",
  buttonPrimary: "#1F5E8D",
  buttonPrimaryText: "#FFFFFF",
  buttonSecondary: "#48607A",
  buttonSecondaryText: "#FFFFFF",
  buttonGhost: "#EEF3F8",
  buttonGhostText: "#0D1A2A",
  cardBackground: "#FFFFFF",
  cardBorder: "#DCE4EC",
  cardHeader: "#FFF2DB",
  inputBackground: "#EEF3F8",
  inputBorder: "#C2CEDA",
  inputText: "#0D1A2A",
  inputPlaceholder: "#607A95",
  tableRow: "#FFFFFF",
  tableRowAlt: "#F6F9FD",
  chipBackground: "#F0F4F8",
  chipActiveBackground: "#FFE9C2",
  chipText: "#314660",
  chipActiveText: "#A86507",
  overlaySoft: "#0D1A2A",
});

const darkIndustrial = Object.freeze({
  canvas: "#0B1422",
  canvasSoft: "#101C2F",
  surface: "#142238",
  surfaceElevated: "#1A2B45",
  surfaceAlt: "#203350",
  surfaceStrong: "#2B4261",
  textPrimary: "#E7EEF8",
  textSecondary: "#B8C8DD",
  textMuted: "#8FA6C2",
  textInverse: "#0B1422",
  border: "#2D4361",
  borderStrong: "#4C6689",
  borderFocus: "#6FB6E2",
  brand: "#4E8DBE",
  brandDark: "#77A7CC",
  brandSoft: "#1B334D",
  accent: "#F3AE43",
  accentSoft: "#3A2A14",
  info: "#53B1E0",
  success: "#31B979",
  warning: "#DE9C3E",
  danger: "#E56A6A",
  focusRing: "#7CC1EC",
  white: "#FFFFFF",
  black: "#000000",
  navActive: "#F3AE43",
  navInactive: "#9EB3CB",
  navIndicator: "#F3AE43",
  buttonPrimary: "#4E8DBE",
  buttonPrimaryText: "#0B1422",
  buttonSecondary: "#2B4261",
  buttonSecondaryText: "#E7EEF8",
  buttonGhost: "#1D3049",
  buttonGhostText: "#E7EEF8",
  cardBackground: "#142238",
  cardBorder: "#304865",
  cardHeader: "#203350",
  inputBackground: "#1A2B45",
  inputBorder: "#3A5778",
  inputText: "#E7EEF8",
  inputPlaceholder: "#90A6BE",
  tableRow: "#16263F",
  tableRowAlt: "#1D304C",
  chipBackground: "#223651",
  chipActiveBackground: "#553D18",
  chipText: "#D7E2F1",
  chipActiveText: "#FFD089",
  overlaySoft: "#000000",
});

const highContrast = Object.freeze({
  canvas: "#FFFFFF",
  canvasSoft: "#F5F5F5",
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surfaceAlt: "#F2F2F2",
  surfaceStrong: "#E6E6E6",
  textPrimary: "#000000",
  textSecondary: "#1A1A1A",
  textMuted: "#333333",
  textInverse: "#FFFFFF",
  border: "#000000",
  borderStrong: "#000000",
  borderFocus: "#005FCC",
  brand: "#005FCC",
  brandDark: "#003D82",
  brandSoft: "#E8F1FF",
  accent: "#FF9F0A",
  accentSoft: "#FFF3E0",
  info: "#005FCC",
  success: "#0B8A42",
  warning: "#B35A00",
  danger: "#B00020",
  focusRing: "#005FCC",
  white: "#FFFFFF",
  black: "#000000",
  navActive: "#000000",
  navInactive: "#333333",
  navIndicator: "#FF9F0A",
  buttonPrimary: "#000000",
  buttonPrimaryText: "#FFFFFF",
  buttonSecondary: "#005FCC",
  buttonSecondaryText: "#FFFFFF",
  buttonGhost: "#FFFFFF",
  buttonGhostText: "#000000",
  cardBackground: "#FFFFFF",
  cardBorder: "#000000",
  cardHeader: "#FFF3E0",
  inputBackground: "#FFFFFF",
  inputBorder: "#000000",
  inputText: "#000000",
  inputPlaceholder: "#333333",
  tableRow: "#FFFFFF",
  tableRowAlt: "#F4F4F4",
  chipBackground: "#F2F2F2",
  chipActiveBackground: "#FFB547",
  chipText: "#000000",
  chipActiveText: "#000000",
  overlaySoft: "#000000",
});

const softNeutral = Object.freeze({
  canvas: "#F7F6F3",
  canvasSoft: "#FBFAF7",
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surfaceAlt: "#F0EFEA",
  surfaceStrong: "#E5E3DB",
  textPrimary: "#1D2A34",
  textSecondary: "#465665",
  textMuted: "#607080",
  textInverse: "#FFFFFF",
  border: "#DCD8CF",
  borderStrong: "#B8B3A8",
  borderFocus: "#6E95B8",
  brand: "#557C9A",
  brandDark: "#3E5D74",
  brandSoft: "#E8EEF3",
  accent: "#C9934D",
  accentSoft: "#F5EADA",
  info: "#6A9ABC",
  success: "#5F8D63",
  warning: "#B5843D",
  danger: "#B66A65",
  focusRing: "#6E95B8",
  white: "#FFFFFF",
  black: "#000000",
  navActive: "#3E5D74",
  navInactive: "#7B8893",
  navIndicator: "#C9934D",
  buttonPrimary: "#557C9A",
  buttonPrimaryText: "#FFFFFF",
  buttonSecondary: "#7F8B96",
  buttonSecondaryText: "#FFFFFF",
  buttonGhost: "#EDEBE5",
  buttonGhostText: "#24323E",
  cardBackground: "#FFFFFF",
  cardBorder: "#DCD8CF",
  cardHeader: "#F5EADA",
  inputBackground: "#F7F6F2",
  inputBorder: "#CAC4B8",
  inputText: "#1D2A34",
  inputPlaceholder: "#7A8895",
  tableRow: "#FFFFFF",
  tableRowAlt: "#F6F4EE",
  chipBackground: "#ECEAE3",
  chipActiveBackground: "#F1DDBE",
  chipText: "#3F4E5B",
  chipActiveText: "#6F4E1E",
  overlaySoft: "#1D2A34",
});

const themes = Object.freeze({
  lightIndustrial: Object.freeze({
    id: "lightIndustrial",
    name: "Light Industrial",
    description: "Blue-slate surfaces with amber action accents.",
    colors: lightIndustrial,
  }),
  darkIndustrial: Object.freeze({
    id: "darkIndustrial",
    name: "Dark Industrial",
    description: "Navy-charcoal surfaces with amber highlights.",
    colors: darkIndustrial,
  }),
  highContrast: Object.freeze({
    id: "highContrast",
    name: "High Contrast",
    description: "Strict black/white with strong action emphasis.",
    colors: highContrast,
  }),
  softNeutral: Object.freeze({
    id: "softNeutral",
    name: "Soft Neutral",
    description: "Low-fatigue neutral canvas with restrained accents.",
    colors: softNeutral,
  }),
});

export const THEME_OPTIONS = Object.freeze([
  Object.freeze({
    id: "lightIndustrial",
    label: "Light Industrial",
    description: "Daylight readability with refined blue + amber accents.",
    swatches: [lightIndustrial.brand, lightIndustrial.accent, lightIndustrial.surface],
  }),
  Object.freeze({
    id: "darkIndustrial",
    label: "Dark Industrial",
    description: "Deep industrial look for low-light environments.",
    swatches: [darkIndustrial.brand, darkIndustrial.accent, darkIndustrial.surface],
  }),
  Object.freeze({
    id: "highContrast",
    label: "High Contrast",
    description: "Maximum contrast for visibility and accessibility.",
    swatches: [highContrast.brand, highContrast.accent, highContrast.surface],
  }),
  Object.freeze({
    id: "softNeutral",
    label: "Soft Neutral",
    description: "Calm neutral palette for low visual fatigue.",
    swatches: [softNeutral.brand, softNeutral.accent, softNeutral.surface],
  }),
]);

export function isThemeId(value) {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(themes, value);
}

export function getThemeDefinition(themeId) {
  if (isThemeId(themeId)) return themes[themeId];
  return themes[DEFAULT_THEME_ID];
}

export function getThemeColors(themeId) {
  return getThemeDefinition(themeId).colors;
}

export default themes;

